version: '3.9'
services:
  app:
    container_name: golang
    build:
      context: ./.docker
      dockerfile: ./app/Dockerfile.prod
    volumes:
      - ./app:/go/src/app
    tty: true
    ports:
      - 1323

  web:
    container_name: nginx
    build:
      context: ./.docker
      dockerfile: ./web/Dockerfile.prod
    volumes:
      - ./.docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/web/define_params:/etc/nginx/define_params
      - ./nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - app