version: '3.9'
services:
  app:
    container_name: golang
    build:
      context: ./.docker
      dockerfile: ./app/Dockerfile.dev
    volumes:
      - ./app:/go/src/app
    tty: true
    ports:
      - 1323
    env_file: .docker/.env

  web:
    container_name: nginx
    build:
      context: ./.docker
      dockerfile: ./web/Dockerfile.dev
    volumes:
      - ./.docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - app

  # ローカル環境のssl化
  https-portal3000:
    image: steveltn/https-portal:1
    ports:
      - '3443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://web:80'